### PR TITLE
Add rocksdb to benchmark

### PR DESCRIPTION
**Pull request by dangershony**
Rocksdb is a more stable implementation then leveldb so I added a bench for it as well.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
wow how the fuck do they manage to get those perf.

**Comment by dangershony** [comment]
> wow how the fuck do they manage to get those perf.

lol yeah the power of c I suppose?
it would be interesting to see if rocks ported to c# will yield close to the same perf stats 🤔

**Comment by dangershony** [comment]
By the way Rocksdb is built on top of leveldb by facebook engineers

**Comment by NicolasDorier** [comment]
Well I am even more surprised about the perf, because the marshalling between C# and C++ calls is not normally not cheap

**Pull request merged**
